checks:
    php: true

filter:
    excluded_paths:
        - tests/*

build:
    environment:
        php:
            version: 7.0.8
    dependencies:
        before:
            - composer require symfony/symfony:3.0.*
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
